/* GENERATED by scripts/gen-unitdefs.mjs — do not edit.
 * Source: BAR engine dumps produced by scripts/dump-unitdefs.lua.
 * Empty until at least one dump has been generated — see src/main/data/README.md.
 */
export interface UnitDefTable {
  /** The replay's `[GAME] { GameType }` string this table was dumped from. */
  gameVersion: string
  engineVersion: string
  /** unitDefID -> [metalCost, offensive ? 1 : 0] */
  units: Record<number, [number, 0 | 1]>
}

export const UNIT_DEF_TABLES: UnitDefTable[] = []
